version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
    volumes:
      - ./user-service:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/user_db
      - SECRET_KEY=supersecretkey
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db


